[project]
name = "collab-book-reader"
version = "0.1.0"
description = "Web App"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=25.1.0",
    "alembic>=1.17.2",
    "alembic-postgresql-enum==1.10.0",
    "asyncpg>=0.31.0",
    "boto3>=1.42.91",
    "core-db",
    "core-ml",
    "edwh-uuid7>=0.2.3",
    "fastapi[standard]>=0.128.0",
    "fonttools>=4.61.1",
    "hf-xet>=1.4.3",
    "onnxruntime>=1.24.1",
    "pillow>=12.1.0",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.12.0",
    "pyjwt>=2.10.1",
    "pypdf>=6.10.2",
    "qdrant-client>=1.17.1",
    "sqlalchemy>=2.0.45",
    "sqlmodel>=0.0.31",
]

[tool.uv.sources]
flash-attn = { url = "https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.7.16/flash_attn-2.8.3%2Bcu128torch2.10-cp313-cp313-linux_x86_64.whl" }
core_db = { path = "../core_db", editable = true }
core_ml = { path = "../core_ml", editable = true}

[dependency-groups]
dev = ["ruff","pytest","pytest-asyncio","pytest-cov","boto3-stubs-full"]

