"""add page table

Revision ID: 045e9ea20cda
Revises: 25bd94a19627
Create Date: 2026-03-05 14:18:20.778316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "045e9ea20cda"
down_revision: Union[str, Sequence[str], None] = "25bd94a19627"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    postgresql.ENUM("complete", "fail", name="pagestatusenum").create(op.get_bind())
    postgresql.ENUM("pending", "text", "quick", "deep", name="pageindexenum").create(
        op.get_bind()
    )
    op.create_table(
        "pages",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("page_no", sa.INTEGER(), nullable=False),
        sa.Column("book_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column(
            "index",
            postgresql.ENUM(
                "pending",
                "text",
                "quick",
                "deep",
                name="pageindexenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("required_deep", sa.BOOLEAN(), nullable=False),
        sa.Column("has_image", sa.BOOLEAN(), nullable=False),
        sa.Column("has_table", sa.BOOLEAN(), nullable=False),
        sa.Column("has_code", sa.BOOLEAN(), nullable=False),
        sa.Column("has_formula", sa.BOOLEAN(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "complete", "fail", name="pagestatusenum", create_type=False
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["book_uid"],
            ["books.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
        sa.UniqueConstraint("book_uid", "page_no", name="uq_book_page"),
    )
    op.create_index(op.f("ix_pages_book_uid"), "pages", ["book_uid"], unique=False)
    op.create_index(op.f("ix_pages_page_no"), "pages", ["page_no"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pages_page_no"), table_name="pages")
    op.drop_index(op.f("ix_pages_book_uid"), table_name="pages")
    op.drop_table("pages")
    sa.Enum("pending", "text", "quick", "deep", name="pageindexenum").drop(
        op.get_bind()
    )
    sa.Enum("complete", "fail", name="pagestatusenum").drop(op.get_bind())
    # ### end Alembic commands ###
