"""changes to books and jobs table

Revision ID: 091b79df4337
Revises: a88d54711dd4
Create Date: 2026-02-06 10:50:34.583735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '091b79df4337'
down_revision: Union[str, Sequence[str], None] = 'a88d54711dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('duplicate', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True))
    op.create_unique_constraint('uq_jobs_user_book_dedupe', 'jobs', ['user_uid', 'book_uid', 'dedupekey'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_user_book_dedupe', 'jobs', type_='unique')
    op.drop_column('books', 'duplicate')
    # ### end Alembic commands ###
