"""add chunks table

Revision ID: 20bffe0e251c
Revises: 045e9ea20cda
Create Date: 2026-03-09 11:36:10.915216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '20bffe0e251c'
down_revision: Union[str, Sequence[str], None] = '045e9ea20cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('page_uid', sa.Uuid(), nullable=False),
    sa.Column('book_uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_data', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_uid'], ['books.uid'], ),
    sa.ForeignKeyConstraint(['page_uid'], ['pages.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_chunks_book_uid'), 'chunks', ['book_uid'], unique=False)
    op.create_index(op.f('ix_chunks_page_uid'), 'chunks', ['page_uid'], unique=False)
    op.create_index(op.f('ix_chunks_user_uid'), 'chunks', ['user_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_user_uid'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_page_uid'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_book_uid'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
