"""add code image array page table

Revision ID: 5fcbaa696db9
Revises: eaa55dbdb2b5
Create Date: 2026-04-30 12:28:48.054914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fcbaa696db9'
down_revision: Union[str, Sequence[str], None] = 'eaa55dbdb2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('code_img_path', postgresql.ARRAY(sa.String(), zero_indexes=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'code_img_path')
    # ### end Alembic commands ###
