"""add img_path column to pages table

Revision ID: 6641acfbade4
Revises: 6ddc33b11ba8
Create Date: 2026-03-17 03:15:14.848444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6641acfbade4'
down_revision: Union[str, Sequence[str], None] = '6ddc33b11ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('img_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'img_path')
    # ### end Alembic commands ###
