"""add partial index

Revision ID: 6ddc33b11ba8
Revises: 20bffe0e251c
Create Date: 2026-03-16 09:45:23.737899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ddc33b11ba8'
down_revision: Union[str, Sequence[str], None] = '20bffe0e251c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_jobs_pending_queue', 'jobs', ['next_run_at', 'created_at'], unique=False, postgresql_where=sa.text("task_status = 'queued' AND locked_by IS NULL"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_jobs_pending_queue', table_name='jobs', postgresql_where=sa.text("task_status = 'queued' AND locked_by IS NULL"))
    # ### end Alembic commands ###
