"""add total page column

Revision ID: 889e3ca5f025
Revises: d26abbfccadc
Create Date: 2026-01-24 07:28:20.957336

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "889e3ca5f025"
down_revision: Union[str, Sequence[str], None] = "d26abbfccadc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("books", sa.Column("total_pages", sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "total_pages")
    # ### end Alembic commands ###
