"""create refreshtoken table

Revision ID: a1fa50cde078
Revises: 02e8577a31f5
Create Date: 2026-01-06 08:14:21.196490

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a1fa50cde078"
down_revision: Union[str, Sequence[str], None] = "02e8577a31f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refreshtokens",
        sa.Column("jti", sa.UUID(), nullable=False),
        sa.Column("expire_at", postgresql.TIMESTAMP(), nullable=False),
        sa.Column("userid", sa.Uuid(), nullable=False),
        sa.Column("revoked", sa.BOOLEAN(), nullable=True),
        sa.ForeignKeyConstraint(
            ["userid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("jti"),
    )
    op.create_index(
        op.f("ix_refreshtokens_userid"), "refreshtokens", ["userid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refreshtokens_userid"), table_name="refreshtokens")
    op.drop_table("refreshtokens")
    # ### end Alembic commands ###
