"""add job table

Revision ID: a88d54711dd4
Revises: 889e3ca5f025
Create Date: 2026-01-24 12:00:22.915330

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a88d54711dd4"
down_revision: Union[str, Sequence[str], None] = "889e3ca5f025"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "queued", "running", "done", "failed", "cancelled", name="taskstatusenum"
    ).create(op.get_bind())
    sa.Enum("low", "high", "urgent", name="jobpriorityenum").create(op.get_bind())
    sa.Enum("bootstrap", "background", "focus", name="jobtypeenum").create(
        op.get_bind()
    )
    op.create_table(
        "jobs",
        sa.Column("job_uid", sa.UUID(), nullable=False),
        sa.Column("book_uid", sa.Uuid(), nullable=False),
        sa.Column("user_uid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("page_total", sa.Integer(), nullable=True),
        sa.Column(
            "job_type",
            postgresql.ENUM(
                "bootstrap",
                "background",
                "focus",
                name="jobtypeenum",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "low", "high", "urgent", name="jobpriorityenum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("page_done", sa.Integer(), nullable=False),
        sa.Column(
            "task_status",
            postgresql.ENUM(
                "queued",
                "running",
                "done",
                "failed",
                "cancelled",
                name="taskstatusenum",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column("page_start", sa.INTEGER(), nullable=False),
        sa.Column("page_end", sa.INTEGER(), nullable=False),
        sa.Column("attempts", sa.INTEGER(), nullable=True),
        sa.Column("error", sa.VARCHAR(), nullable=True),
        sa.Column(
            "next_run_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("locked_by", sa.VARCHAR(), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dedupekey", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_uid"],
            ["books.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["user_uid"],
            ["users.uid"],
        ),
        sa.PrimaryKeyConstraint("job_uid"),
    )
    op.create_index(op.f("ix_jobs_book_uid"), "jobs", ["book_uid"], unique=False)
    op.create_index(op.f("ix_jobs_user_uid"), "jobs", ["user_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_user_uid"), table_name="jobs")
    op.drop_index(op.f("ix_jobs_book_uid"), table_name="jobs")
    op.drop_table("jobs")
    sa.Enum("bootstrap", "background", "focus", name="jobtypeenum").drop(op.get_bind())
    sa.Enum("low", "high", "urgent", name="jobpriorityenum").drop(op.get_bind())
    sa.Enum(
        "queued", "running", "done", "failed", "cancelled", name="taskstatusenum"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
