"""modified refreshtoken schema

Revision ID: afeef297079c
Revises: a1fa50cde078
Create Date: 2026-01-06 10:50:04.466948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "afeef297079c"
down_revision: Union[str, Sequence[str], None] = "a1fa50cde078"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refreshtokens", "revoked", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "refreshtokens", "revoked", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
