"""modified books table index

Revision ID: ce12e6c2d2dd
Revises: afeef297079c
Create Date: 2026-01-07 08:16:48.551385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ce12e6c2d2dd"
down_revision: Union[str, Sequence[str], None] = "afeef297079c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_books_user_uid"), "books", ["user_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_user_uid"), table_name="books")
    # ### end Alembic commands ###
