"""add status column

Revision ID: d26abbfccadc
Revises: e5699eae014e
Create Date: 2026-01-23 10:37:30.351917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd26abbfccadc'
down_revision: Union[str, Sequence[str], None] = 'e5699eae014e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'processing', 'ready_partial', 'ready_full', 'failed', name='bookstatusmodel').create(op.get_bind())
    op.add_column('books', sa.Column('status', postgresql.ENUM('pending', 'processing', 'ready_partial', 'ready_full', 'failed', name='bookstatusmodel', create_type=False), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'status')
    sa.Enum('pending', 'processing', 'ready_partial', 'ready_full', 'failed', name='bookstatusmodel').drop(op.get_bind())
    # ### end Alembic commands ###
