"""book filename index add

Revision ID: e5699eae014e
Revises: ce12e6c2d2dd
Create Date: 2026-01-10 05:25:24.910253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e5699eae014e"
down_revision: Union[str, Sequence[str], None] = "ce12e6c2d2dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_books_filename"), "books", ["filename"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_filename"), table_name="books")
    # ### end Alembic commands ###
