"""add column pages and chunks table

Revision ID: eaa55dbdb2b5
Revises: d5dc864d474c
Create Date: 2026-04-03 04:21:06.514347

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eaa55dbdb2b5"
down_revision: Union[str, Sequence[str], None] = "d5dc864d474c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chunks", sa.Column("page_no", sa.INTEGER(), nullable=False))
    op.add_column(
        "pages",
        sa.Column(
            "table_img_path",
            postgresql.ARRAY(sa.String(), zero_indexes=True),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pages", "table_img_path")
    op.drop_column("chunks", "page_no")
    # ### end Alembic commands ###
